import { createContext, useContext, type ReactNode } from 'react';
import { Text as RNText, type TextProps } from 'react-native';
import type { FontScript, FontWeightName } from '../tokens';

/**
 * The active script, provided by the app from its i18n language.
 *
 * `packages/ui-native` deliberately does not import i18next: it is shared by
 * both apps and must not be bound to either one's i18n instance. The app maps
 * language -> script (see SCRIPT_FOR_LOCALE in ./format) and provides it here.
 */
const FontScriptContext = createContext<FontScript>('latin');

export function FontScriptProvider({
  script,
  children,
}: {
  script: FontScript;
  children: ReactNode;
}) {
  return <FontScriptContext.Provider value={script}>{children}</FontScriptContext.Provider>;
}

export function useFontScript(): FontScript {
  return useContext(FontScriptContext);
}

/**
 * Family classes generated by the shared Tailwind preset.
 *
 * Written out as whole literals rather than composed at runtime because
 * Tailwind's content scanner reads this file as text — a template literal
 * would produce no CSS and every string would silently fall back to the
 * system font.
 */
const FAMILY_CLASS: Record<FontScript, Record<FontWeightName, string>> = {
  latin: {
    regular: 'font-latin',
    medium: 'font-latin-medium',
    semibold: 'font-latin-semibold',
    bold: 'font-latin-bold',
  },
  devanagari: {
    regular: 'font-deva',
    medium: 'font-deva-medium',
    semibold: 'font-deva-semibold',
    bold: 'font-deva-bold',
  },
};

/**
 * Two utilities of the same Tailwind property win by stylesheet order, not by
 * their order in the className string — so "our default first, caller's
 * second" is not a rule NativeWind honours. Instead of gambling on order, the
 * defaults are simply not emitted when the caller has already set that
 * property.
 *
 * `text-*` is ambiguous in Tailwind: it is both the font-size scale and the
 * text-colour scale. The size names are a closed set, so one regex matches
 * sizes and the other matches everything else beginning `text-`.
 */
const SIZE_CLASSES = new Set([
  'text-xs',
  'text-sm',
  'text-base',
  'text-lg',
  'text-xl',
  'text-2xl',
  'text-3xl',
  'text-4xl',
  'text-5xl',
]);

/** Matched against whole class tokens rather than with a regex: a `text-`
 *  pattern is fiddly to escape correctly and silently matches the wrong
 *  thing when it is not. Splitting on whitespace has neither problem. */
function classifyGivenClasses(className: string): { hasSize: boolean; hasColor: boolean } {
  let hasSize = false;
  let hasColor = false;

  for (const token of className.split(/\s+/)) {
    if (!token.startsWith('text-')) continue;
    if (SIZE_CLASSES.has(token)) hasSize = true;
    else hasColor = true;
  }

  return { hasSize, hasColor };
}

export interface TextComponentProps extends TextProps {
  /** Maps to a font family, not to `fontWeight`: custom families on Android
   *  do not synthesise weights, they have to be named. */
  weight?: FontWeightName;
}

/**
 * The only Text in the app.
 *
 * It exists to guarantee two things that are easy to forget per-screen and
 * expensive to retrofit:
 *
 *   1. a font family that matches the script being rendered, so Devanagari
 *      never falls through to whatever font the OEM happens to ship;
 *   2. a size class, and therefore the preset's 1.5x leading, even when the
 *      caller sets none — bare React Native Text has no lineHeight at all,
 *      which is where conjuncts get clipped.
 *
 * Import this rather than `Text` from react-native.
 */
export function Text({ weight = 'regular', className, ...rest }: TextComponentProps) {
  const script = useFontScript();
  const given = className ?? '';
  const { hasSize, hasColor } = classifyGivenClasses(given);

  const classes = [
    FAMILY_CLASS[script][weight],
    hasSize ? '' : 'text-base',
    hasColor ? '' : 'text-brand-navy',
    given,
  ]
    .filter(Boolean)
    .join(' ');

  return <RNText className={classes} {...rest} />;
}
